import type { DemoEvent, Player } from "./types";

export const leagues = [
  "FIFA World Cup",
  "Premier League",
  "Champions League",
  "LaLiga",
  "Serie A",
  "Bundesliga",
  "MLS",
  "EURO",
];

export const demoEvents: DemoEvent[] = [
  {
    id: "kickoff",
    minute: 0,
    type: "kickoff",
    title: "Kickoff: predictions locked",
    description:
      "TxLINE confirms kickoff. Saved score, winner, total goals, and live-round picks are now locked.",
    snapshot: {
      minute: 0,
      homeScore: 0,
      awayScore: 0,
      status: "live",
      statusLabel: "0'",
      homeWinProbability: 42,
      drawProbability: 29,
      awayWinProbability: 29,
      marketNote: "All pre-match predictions locked",
      totalCards: 0,
      totalCorners: 0,
    },
    scoringHint: "No points settled yet",
  },
  {
    id: "france-goal",
    minute: 16,
    type: "goal",
    title: "16' Goal France",
    description:
      "France lead 1-0. The first-goal pick settles, while Morocco winner and exact-score picks need a comeback.",
    snapshot: {
      minute: 16,
      homeScore: 1,
      awayScore: 0,
      status: "live",
      statusLabel: "16'",
      homeWinProbability: 58,
      drawProbability: 25,
      awayWinProbability: 17,
      marketNote: "Your 1-2 exact score now needs two Morocco goals",
      totalCards: 0,
      totalCorners: 1,
    },
    scoringHint: "+4 live-round points if you picked first goal: France",
    nextGoalScorer: "home",
  },
  {
    id: "morocco-equalizer",
    minute: 42,
    type: "goal",
    title: "42' Goal Morocco",
    description:
      "Morocco equalize before halftime. Exact-score and Morocco winner picks regain value.",
    snapshot: {
      minute: 42,
      homeScore: 1,
      awayScore: 1,
      status: "live",
      statusLabel: "42'",
      homeWinProbability: 38,
      drawProbability: 34,
      awayWinProbability: 28,
      marketNote: "Your 1-2 exact score is one Morocco goal away",
      totalCards: 1,
      totalCorners: 4,
    },
    scoringHint: "Winner pick still open, exact score one event away",
    nextGoalScorer: "away",
  },
  {
    id: "france-red",
    minute: 55,
    type: "card",
    title: "55' Red card France",
    description:
      "TxLINE card event lowers France win probability. The private league swings toward players holding Morocco picks.",
    snapshot: {
      minute: 55,
      homeScore: 1,
      awayScore: 1,
      status: "live",
      statusLabel: "55'",
      homeWinProbability: 27,
      drawProbability: 39,
      awayWinProbability: 34,
      marketNote: "Morocco winner probability rises after the red card",
      totalCards: 2,
      totalCorners: 5,
    },
    scoringHint: "Winner pick gains live value, exact score remains open",
  },
  {
    id: "corners-surge",
    minute: 63,
    type: "corner",
    title: "63' Corner pressure rising",
    description:
      "Corner volume jumps after three attacks in five minutes. A bonus round opens for higher/lower corners.",
    snapshot: {
      minute: 63,
      homeScore: 1,
      awayScore: 1,
      status: "live",
      statusLabel: "63'",
      homeWinProbability: 25,
      drawProbability: 40,
      awayWinProbability: 35,
      marketNote: "Mini round open: next card or higher/lower corners",
      totalCards: 2,
      totalCorners: 9,
    },
    scoringHint: "Bonus round available for 02:15",
  },
  {
    id: "morocco-winner",
    minute: 78,
    type: "goal",
    title: "78' Goal Morocco",
    description:
      "Morocco take the lead. TxLINE pushes the live leaderboard because your exact-score, winner, and total-goals picks now all line up.",
    snapshot: {
      minute: 78,
      homeScore: 1,
      awayScore: 2,
      status: "live",
      statusLabel: "78'",
      homeWinProbability: 13,
      drawProbability: 20,
      awayWinProbability: 67,
      marketNote: "Your 1-2 exact score is now live-leading",
      totalCards: 4,
      totalCorners: 10,
    },
    scoringHint: "+13 projected points from score, winner, and total goals",
    nextGoalScorer: "home",
  },
  {
    id: "full-time",
    minute: 90,
    type: "full-time",
    title: "Full time: France 1-2 Morocco",
    description:
      "TxLINE final score settles predictions and freezes the private league leaderboard.",
    snapshot: {
      minute: 90,
      homeScore: 1,
      awayScore: 2,
      status: "finished",
      statusLabel: "FT",
      homeWinProbability: 0,
      drawProbability: 0,
      awayWinProbability: 100,
      marketNote: "Final settlement complete",
      totalCards: 4,
      totalCorners: 11,
    },
    scoringHint: "Final score settled",
  },
];

export const players: Player[] = [
  { name: "Thierno", baseScore: 34, trend: "Exact score live" },
  { name: "Amina", baseScore: 39, trend: "Winner pick" },
  { name: "Sam", baseScore: 34, trend: "Locked" },
  { name: "Noah", baseScore: 31, trend: "Draw hedge" },
];

export const form = [
  { team: "France", scores: ["1-0", "2-1", "3-0", "1-1", "0-0"] },
  { team: "Morocco", scores: ["3-0", "2-1", "1-0", "2-2", "1-1"] },
];
