import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";

import {
  DAY_MS,
  HOUR_MS,
  createClient,
  fail,
  readEnv,
  sweepBuckets,
} from "./lib/txline-bulk.mjs";

// Rebuilds finished World Cup fixtures from TxLINE and writes them to
// public/replays as replayable packs.
//
// Why this exists: /scores/historical only serves fixtures that kicked off
// between two weeks and six hours ago, and /fixtures/snapshot drops finished
// fixtures within hours. Everything older is still in the bulk feed, but only
// if you sweep the five-minute buckets around kickoff — ~84 requests per
// fixture. Too slow to do at request time, and the hackathon's free data
// window closes on 2026-07-19, so the packs are committed rather than fetched.

const appRoot = process.cwd();
const outDir = path.join(appRoot, "public", "replays");
const seedPath = path.join(appRoot, "src", "lib", "replay-fixtures.ts");

const STAGES = {
  10115573: "Semi-finals",
  10115574: "16th Finals",
  10115674: "Group Stage",
  10115675: "Quarter-finals",
  10115676: "Final",
  10115677: "32nd Finals",
  10115771: "Final",
};
const COMPETITION_ID = 72;
// Below this a rebuild is a stub (no coverage) rather than a real match.
const MIN_RECORDS = 100;

const client = createClient(readEnv(appRoot));

async function fetchFixtures() {
  const today = Math.floor(Date.now() / DAY_MS);
  const fixtures = new Map();

  // startEpochDay opens a ~30-day window; step under that to avoid gaps.
  for (let day = today - 90; day <= today + 40; day += 25) {
    const payloads = await client.get(
      `${client.origin}/api/fixtures/snapshot?startEpochDay=${day}`,
    );

    for (const fixture of payloads) {
      if (fixture.CompetitionId === COMPETITION_ID && fixture.FixtureId) {
        fixtures.set(fixture.FixtureId, fixture);
      }
    }
  }

  return [...fixtures.values()].sort((a, b) => a.StartTime - b.StartTime);
}

// Every record repeats the same fixture metadata. Hoisting the fields that
// never vary cuts each pack by ~25% and rehydrates losslessly.
function pack(records) {
  const constant = {};

  for (const key of Object.keys(records[0])) {
    const value = JSON.stringify(records[0][key]);

    if (records.every((record) => JSON.stringify(record[key]) === value)) {
      constant[key] = records[0][key];
    }
  }

  return {
    meta: constant,
    records: records.map((record) => {
      const rest = {};

      for (const key of Object.keys(record)) {
        if (!(key in constant)) {
          rest[key] = record[key];
        }
      }

      return rest;
    }),
  };
}

function summarise(records) {
  const discarded = new Set(
    records.filter((record) => record.Action === "action_discarded").map((record) => record.Id),
  );
  // One real event emits several records sharing an Id (unconfirmed, then
  // confirmed), and only the last carries Data.PlayerId. Count Ids, not
  // records, and drop the ones a scout later discarded — a disallowed goal
  // correctly has no scorer, and counting it reads as a missing attribution.
  const liveIds = (action) =>
    [...new Set(records.filter((record) => record.Action === action).map((record) => record.Id))]
      .filter((id) => !discarded.has(id));
  const attributed = (ids, action) =>
    ids.filter((id) =>
      records.some(
        (record) => record.Action === action && record.Id === id && record.Data?.PlayerId,
      ),
    ).length;
  const goals = liveIds("goal");
  const yellows = liveIds("yellow_card");
  const reds = liveIds("red_card");
  const finalised = records.find((record) => record.Action === "game_finalised");
  const score = finalised?.Score ?? {};

  return {
    cards: yellows.length + reds.length,
    cardsAttributed: attributed(yellows, "yellow_card") + attributed(reds, "red_card"),
    finalised: Boolean(finalised),
    goals: goals.length,
    goalsAttributed: attributed(goals, "goal"),
    hasLineups: records.some((record) => record.Action === "lineups"),
    reds: reds.length,
    score: [score.Participant1?.Total?.Goals ?? 0, score.Participant2?.Total?.Goals ?? 0],
  };
}

function seedFile(entries) {
  const rows = entries
    .map((entry) =>
      [
        "  {",
        `    fixtureId: ${entry.fixtureId},`,
        `    fixtureGroup: ${JSON.stringify(`World Cup > ${entry.stage}`)},`,
        `    homeTeam: ${JSON.stringify(entry.homeTeam)},`,
        `    awayTeam: ${JSON.stringify(entry.awayTeam)},`,
        `    kickoffUtc: ${JSON.stringify(new Date(entry.kickoff).toISOString())},`,
        `    stage: ${JSON.stringify(entry.stage)},`,
        "  },",
      ].join("\n"),
    )
    .join("\n");

  return `import type { WorldCupFixture } from "./world-cup-fixtures";

// Generated by scripts/harvest-replays.mjs — do not edit by hand.
// Every fixture here has a matching pack in public/replays.
export const replayFixtures: WorldCupFixture[] = [
${rows}
];

export const replayFixtureIds = new Set(
  replayFixtures.map((fixture) => fixture.fixtureId),
);
`;
}

const fixtures = await fetchFixtures();
const finished = fixtures.filter((fixture) => fixture.StartTime < Date.now() - 3 * HOUR_MS);

console.log(`World Cup fixtures: ${fixtures.length} (${finished.length} finished)`);
fs.mkdirSync(outDir, { recursive: true });

const manifest = [];
const skipped = [];
let index = 0;

for (const fixture of finished) {
  index += 1;

  const stage = STAGES[fixture.FixtureGroupId] ?? String(fixture.FixtureGroupId);
  const homeTeam = fixture.Participant1IsHome ? fixture.Participant1 : fixture.Participant2;
  const awayTeam = fixture.Participant1IsHome ? fixture.Participant2 : fixture.Participant1;
  const label = `[${String(index).padStart(3)}/${finished.length}] ${homeTeam} v ${awayTeam}`;
  const { failures, records: raw } = await sweepBuckets(client, {
    feed: "scores",
    fixtureId: fixture.FixtureId,
    kickoff: fixture.StartTime,
  });

  // Buckets overlap at their edges, so the same Seq can arrive twice.
  const bySeq = new Map();

  for (const record of raw) {
    if (!bySeq.has(record.Seq)) {
      bySeq.set(record.Seq, record);
    }
  }

  const records = [...bySeq.values()].sort(
    (left, right) => (left.Seq ?? 0) - (right.Seq ?? 0),
  );

  // A pack built from a partial sweep would silently miss goals, so refuse it.
  if (failures > 0) {
    skipped.push({ label, reason: `${failures} buckets unreachable` });
    console.log(`${label} — SKIPPED, ${failures} buckets unreachable`);
    continue;
  }

  if (records.length < MIN_RECORDS) {
    skipped.push({ label, reason: `no coverage (${records.length} records)` });
    console.log(`${label} — no coverage (${records.length} records)`);
    continue;
  }

  const stats = summarise(records);

  if (!stats.hasLineups || !stats.finalised) {
    skipped.push({
      label,
      reason: `incomplete (lineups ${stats.hasLineups}, finalised ${stats.finalised})`,
    });
    console.log(
      `${label} — incomplete (lineups ${stats.hasLineups}, finalised ${stats.finalised})`,
    );
    continue;
  }

  const body = zlib.gzipSync(JSON.stringify(pack(records)), { level: 9 });

  fs.writeFileSync(path.join(outDir, `${fixture.FixtureId}.json.gz`), body);
  manifest.push({
    awayTeam,
    cards: stats.cards,
    cardsAttributed: stats.cardsAttributed,
    fixtureId: fixture.FixtureId,
    goals: stats.goals,
    goalsAttributed: stats.goalsAttributed,
    homeTeam,
    kickoff: fixture.StartTime,
    records: records.length,
    reds: stats.reds,
    score: stats.score,
    sizeKb: Math.round(body.length / 1024),
    stage,
  });
  console.log(
    `${label} ${stats.score[0]}-${stats.score[1]} — ${records.length} records, ` +
      `goals ${stats.goalsAttributed}/${stats.goals}, cards ${stats.cardsAttributed}/${stats.cards}, ` +
      `${Math.round(body.length / 1024)}KB`,
  );
}

if (manifest.length === 0) {
  fail("No replays packed — refusing to overwrite the seed.");
}

manifest.sort((left, right) => left.kickoff - right.kickoff);
fs.writeFileSync(path.join(outDir, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
fs.writeFileSync(seedPath, seedFile(manifest));

const totalKb = manifest.reduce((sum, entry) => sum + entry.sizeKb, 0);
const goals = manifest.reduce((sum, entry) => sum + entry.goals, 0);
const goalsAttributed = manifest.reduce((sum, entry) => sum + entry.goalsAttributed, 0);

console.log(`\nPacked ${manifest.length}/${finished.length} replays, ${Math.round(totalKb / 1024 * 10) / 10}MB`);
console.log(`Goal attribution: ${goalsAttributed}/${goals}`);
console.log(
  `Requests: ${client.stats.requests} (${client.stats.retries} retries, ${client.stats.throttled} throttled)`,
);

if (skipped.length > 0) {
  console.log(`\nSkipped ${skipped.length}:`);

  for (const entry of skipped) {
    console.log(`  ${entry.label} — ${entry.reason}`);
  }
}
